export const CART_ITEMS_REQUEST = "CART_ITEMS_REQUEST";
export const CART_ITEMS_SUCCESS = "CART_ITEMS_SUCCESS";
export const CART_ITEMS_FAIL = "CART_ITEMS_FAIL";

export const CREATE_CART_ITEMS_REQUEST = "CREATE_CART_ITEMS_REQUEST";
export const CREATE_CART_ITEMS_SUCCESS = "CREATE_CART_ITEMS_SUCCESS";
export const CREATE_CART_ITEMS_FAIL = "CREATE_CART_ITEMS_FAIL";

export const UPDATE_CART_ITEMS_REQUEST = "UPDATE_CART_ITEMS_REQUEST";
export const UPDATE_CART_ITEMS_SUCCESS = "UPDATE_CART_ITEMS_SUCCESS";
export const UPDATE_CART_ITEMS_FAIL = "UPDATE_CART_ITEMS_FAIL";

export const DELETE_CART_ITEMS_REQUEST = "DELETE_CART_ITEMS_REQUEST";
export const DELETE_CART_ITEMS_SUCCESS = "DELETE_CART_ITEMS_SUCCESS";
export const DELETE_CART_ITEMS_FAIL = "DELETE_CART_ITEMS_FAIL";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
